name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    # TODO: (aver) add private image push!
    steps:
      - uses: actions/checkout@v3

      - name: Login to ghcr.io
        run: docker login --username arminveres --password ${{ secrets.GH_PAT }} ghcr.io

      - name: Build and push the Agent Docker image
        run: |
          docker build . --file docker/agent.dockerfile --tag ghcr.io/arminveres/bachelor-thesis-23/node-agent:latest
          docker push ghcr.io/arminveres/bachelor-thesis-23/node-agent:latest

      - name: Build and Push the Auditor Docker image
        run: |
          docker build . --file docker/auditor.dockerfile --tag ghcr.io/arminveres/bachelor-thesis-23/auditor:latest
          docker push ghcr.io/arminveres/bachelor-thesis-23/auditor:latest

      - name: Build and Push the Updater Docker image
        run: |
          docker build . --file docker/updater.dockerfile --tag ghcr.io/arminveres/bachelor-thesis-23/updater:latest
          docker push ghcr.io/arminveres/bachelor-thesis-23/updater:latest
