name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    # TODO: (aver) add private image push!
    steps:
      - uses: actions/checkout@v3
      - name: Build the Agent Docker image
        run: docker build impl --file impl/docker/agent.dockerfile --tag ba-agent:$(date +%s)
      - name: Build the Auditor Docker image
        run: docker build impl --file impl/docker/auditor.dockerfile --tag ba-auditor:$(date +%s)
      - name: Build the Updater Docker image
        run: docker build impl --file impl/docker/updater.dockerfile --tag ba-updater:$(date +%s)
